### ISSUE TITLE
Missing key value

### ISSUE THREAD

**Issue by ishank-juneja** [shreyasc-13/correlated_bandits#1]
There is a missing Key value here that is referenced but not assigned anywhere in the code. Throws keyError when I try to run after fixing some other keyErros

https://github.com/shreyasc-13/correlated_bandits/blob/671e0035c733163d53334bcb8515f745fdde1654/preproc/preproc.py#L186

**Comment by shreyasc-13** [comment]
The key needed was "movie_col", assigned [here](https://github.com/shreyasc-13/correlated_bandits/blob/affa3c43729e194791466da66c8bdac5c541acf0/preproc/preproc.py#L154). Updated, thanks for pointing it out!
