### ISSUE TITLE
Binary file not saved but accesed

### ISSUE THREAD

**Issue by ishank-juneja** [shreyasc-13/correlated_bandits#3]
Unlike the line,
https://github.com/shreyasc-13/correlated_bandits/blob/671e0035c733163d53334bcb8515f745fdde1654/preproc/preproc.py#L73
Where the processed dataset `genres/data_with_id` is saved, in the below line the corresponding dataset for movies is accesed but never saved prior, 

https://github.com/shreyasc-13/correlated_bandits/blob/671e0035c733163d53334bcb8515f745fdde1654/preproc/preproc.py#L140

**Comment by shreyasc-13** [comment]
The file would be the same as <tt>genres/data_with_id</tt> as the movie columns are added later in the function. Updated, thanks for pointing it out!
